### ISSUE TITLE
Suggestion: put this in a maven repository

### ISSUE THREAD

**Issue by belzoriun** [streamx-co/ExTree#3]
After trying this in a project of my own, i found it extremly useful ! That is a great piece of work for sure.
The only issue I had is implementing it into an existing project, I had to go through the code and rename every package and fix broken imports. Idk if it is possible, but making a maven repository for this project would be insanely useful.

**Comment by kostat** [comment]
Hey @belzoriun , ex-tree is already  in maven repo - https://central.sonatype.com/search?q=%22ex-tree%22
