### ISSUE TITLE
Not matching licence between the source code and pom.xml

### ISSUE THREAD

**Issue by balevas** [streamx-co/ExTree#4]
According to https://github.com/streamx-co/ExTree/blob/master/LICENSE and https://github.com/streamx-co/ExTree/blob/master/README.md, ExTree is distributed under the terms of the LGPL license.
In https://github.com/streamx-co/ExTree/blob/master/pom.xml, however, https://www.gnu.org/licenses/agpl-3.0.en.html is referenced, which is an even stronger copyleft licence than GPL, making the ExTree library a no choice for proprietary software.

Please make it clear which of these 2 licenses applies for ExTree.

**Comment by kostat** [comment]
Released a new version with the fix - https://github.com/streamx-co/ExTree/releases/tag/ex-tree-2.8.3
