### ISSUE TITLE
calling LambdaExpression.Parse(...) on a reference to a method that takes no parameters and returns void results in a NullPointerException

### ISSUE THREAD

**Issue by qwerty-debug** [streamx-co/ExTree#5]
JDK: 21
Version: 2.8.0, 2.8.3
Expected behaviour: parsing the method reference results in an expression similar to the expression from parsing a lambda
Actual behaviour: parsing the method reference results in a NullPointerException

```
public class Test {
    public static void method() {

    }

    @FunctionalInterface
    interface Callable extends Serializable {
        void call();
    }

    public static void main(String... args) {
        Callable callable1 = () -> method();
        Callable callable2 = Test::method;
        var expression1 = LambdaExpression.parse(callable1); // works as expected
        var expression2 = LambdaExpression.parse(callable2); // NullPointerException
    }
}
```

The issue is likely related to this line in ExpressionClassCracker:
```
        Expression reducedExpression = type == Void.TYPE ? null
                : TypeConverter.convert(actualVisitor.getResult(), type);
```
https://github.com/streamx-co/ExTree/blob/master/src/main/java/co/streamx/fluent/extree/expression/ExpressionClassCracker.java

**Comment by kostat** [comment]
Thank you for reporting this and nice catch! Looks like `reducedExpression` should always be initialized to `actualVisitor.getResult()`.
